### ISSUE TITLE
Error running make on OSX

### ISSUE THREAD

**Issue by alexcoplan** [Ramblurr/PietCreator#1]
I installed all the required dependencies, and cmake ran fine, but when running make, it got to 95%, and gave this error:

Linking CXX executable pietcreator
Undefined symbols for architecture x86_64:
  "_PrintGifError", referenced from:
      _read_gif in libnpiet.a(npiet.c.o)
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[2]: **\* [pietcreator] Error 1
make[1]: **\* [CMakeFiles/pietcreator.dir/all] Error 2
make: **\* [all] Error 2

**Comment by alexcoplan** [comment]
Just tried this on another machine and the same error.

**Comment by xxBedy** [comment]
On Yosemite with Homebrew installed failed with:

Scanning dependencies of target npiet
[  2%] Building C object npiet/CMakeFiles/npiet.dir/npiet.c.o
/Users/mbednar/Git/PietCreator/npiet/npiet.c:1114:19: error: incomplete definition of type 'struct png_info_def'
  width = info_ptr->width;
          ~~~~~~~~^
/usr/local/include/png.h:591:16: note: forward declaration of 'struct png_info_def'
typedef struct png_info_def png_info;
               ^
/Users/mbednar/Git/PietCreator/npiet/npiet.c:1115:20: error: incomplete definition of type 'struct png_info_def'
  height = info_ptr->height;
           ~~~~~~~~^
/usr/local/include/png.h:591:16: note: forward declaration of 'struct png_info_def'
typedef struct png_info_def png_info;
               ^
/Users/mbednar/Git/PietCreator/npiet/npiet.c:1116:24: error: incomplete definition of type 'struct png_info_def'
  ncol = 2 << (info_ptr->bit_depth - 1);
               ~~~~~~~~^
/usr/local/include/png.h:591:16: note: forward declaration of 'struct png_info_def'
typedef struct png_info_def png_info;
               ^
3 errors generated.
make[2]: **\* [npiet/CMakeFiles/npiet.dir/npiet.c.o] Error 1
make[1]: **\* [npiet/CMakeFiles/npiet.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Ivoah** [comment]
I have the same issue on Yosemite

**Comment by Ivoah** [comment]
If you replace lines 1114, 1116, and 1116 in npiet/npiet.c with

```
  width = png_get_image_width(png_ptr, info_ptr);
  height = png_get_image_height(png_ptr, info_ptr);
  ncol = 2 << (png_get_bit_depth(png_ptr, info_ptr) - 1);
```

It will make it work with the latest libpng. I have submitted a pull request containing the changes.

**Comment by Ramblurr** [comment]
Thanks for updating this guys! Nice to see there is interest in Piet :)

**Comment by Ivoah** [comment]
Are you going to merge my pull request?

**Comment by Ivoah** [comment]
This issue can be closed now.
